export interface Usuariost {

    idUsuarios?: number,
    Nombres : string,
    Apellidos : string,
    Estado: number,
    NumeroDocumento : number,
    FechaIngreso : number,
    NombreUsuarioSistema : string,
    Direccion : string,
    TelefonoFijo : number,
    TelefonoFijo2?: number,
    TelefonoMovil: number,
    TelefonoMovil2?: number ,
    Email : string,
    NombrePE ?: number,
    NombreCentroZonal ?: number,
    NombreUDS ?: number,
    NombreTipo : number,
    TipoUsuario : string,
    password?: string,
  }
